# Force dep to vendor the code generators, which aren't imported just used at dev time.
# Picking a subpackage with Go code won't be necessary once https://github.com/golang/dep/pull/1545 is merged.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
  "github.com/kevinburke/go-bindata",
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[prune.project]]
  name = "k8s.io/code-generator"
  non-go = false

[[prune.project]]
  name = "github.com/kevinburke/go-bindata"
  non-go = false
  unused-packages = false

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.1.9"

[[constraint]]
  name = "github.com/openshift/api"
  revision = "ad6339a9e4ce20fffe56b91dc9c9ee7a4d04ebd7"

[[constraint]]
  name = "github.com/kevinburke/go-bindata"
  version = "v3.11.0"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.5"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.5"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.5"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.5"
