kind: ConfigMap
apiVersion: v1
metadata:
  name: dns
  namespace: openshift-cluster-dns
data:
  Corefile: |
    .:53 {
        errors
        health
        #TODO: Set user configured DNS domain
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            upstream
            fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
    }
