# Role for the operator in openshift-cluster-dns namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-dns-operator:openshift-cluster-dns
  namespace: openshift-cluster-dns
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
