# Role for the operator itself.
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dns-operator
  namespace: openshift-dns-operator
rules:
- apiGroups:
  - dns.openshift.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - services
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
