# Account for the operator itself. It should require namespace scoped
# permissions.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cluster-dns-operator
  namespace: openshift-cluster-dns-operator

---

# Cluster role for the operator itself.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-dns-operator
  namespace: openshift-cluster-dns-operator
rules:
- apiGroups:
  - dns.openshift.io
  resources:
  - clusterdnses
  verbs:
  - list
  - watch

---

# Binds the operator cluster role to its Service Account.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-dns-operator
subjects:
- kind: ServiceAccount
  name: cluster-dns-operator
  namespace: openshift-cluster-dns-operator
roleRef:
  kind: ClusterRole
  name: cluster-dns-operator
  namespace: openshift-cluster-dns-operator
userNames:
- "system:serviceaccount:openshift-cluster-dns-operator:cluster-dns-operator"
