# Installer config specific values are applied at runtime.
apiVersion: dns.openshift.io/v1alpha1
kind: ClusterDNS
metadata:
  name: default
  # Ensure that only the operator can delete the default cluster dns object.
  finalizers:
  - dns.openshift.io/default-cluster-dns
